version: '3.1'

services:
  web:
    container_name: emoji-frontend
    build: .
    #image: pauloclouddev/random-emoji-app:1.1 # Add this line for pushing with docker compose
    ports:
      - "80:5000" # for beanstalk deployment
      # - "8000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development

  redis:
    container_name: redis-db-backend
    image: "redis:alpine"
